FROM alpine:3

LABEL author="Dimas Aryo Mahendro"
LABEL company="Institut Teknologi Kalimantan" website="www.if.ac.id"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"